[versions]
agp = "9.2.1"
annotation = "1.10.0"
hiddenapiBypass = "6.1"
kotlin = "2.4.20"
ksp = "2.3.12"
xposed = "82"
lsposed = "102.0.0"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
android-build-tools = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
devtools-ksp = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
hidden-api-bypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version.ref = "hiddenapiBypass" }
symbol-processing-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }
lsposed-api = { group = "io.github.libxposed", name = "api", version.ref = "lsposed" }